/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package u4_ld_app;

import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rober
 */
public class U4_LD_Frame extends javax.swing.JFrame {

    /**
     * Creates new form U4_LD_Frame
     */
    
    ArrayList<Integer> Priridad = new ArrayList<>();
    String resultado = "";
    
    FuzzyLogic fl;
    
    boolean inicio = false;
    
    public U4_LD_Frame() {
        initComponents();
    }
    
    private double prioridad(double tmpEsperas, double tmpViajes, double cargas, double distViaje, double cargaActual){
    // Membresias
            String[] membresiaTmpEspera = FuzzyLogic.MembresiaTeTvDv(tmpEsperas);
            String[] membresiaTmpViajes = FuzzyLogic.MembresiaTeTvDv(tmpViajes);
            String[] membresiaCarga = FuzzyLogic.MembresiaCDLL(cargas);
            String[] membresiaDisViaje = FuzzyLogic.MembresiaTeTvDv(distViaje);
            String[] membresiaCargaPactual = FuzzyLogic.MembresiaCDLL(cargaActual);

            resultado += "\nMembresias\n";
            resultado += Calculos.membresiaS("Tiempo Espera:", membresiaTmpEspera);
            resultado += Calculos.membresiaS("Tiempo Viaje: ", membresiaTmpViajes);
            resultado += Calculos.membresiaS("Carga: ", membresiaCarga);
            resultado += Calculos.membresiaS("Diastancia Viaje:", membresiaDisViaje);
            resultado += Calculos.membresiaS("Carga Piso Acutal:", membresiaCargaPactual);

            // Reglas -> Inferencia
            String [][] reglasTmpEspera = Calculos.membresiaResultado(membresiaTmpEspera);
            String [][] reglasTmpViajes = Calculos.membresiaResultado(membresiaTmpViajes);
            String [][] reglasCarga = Calculos.membresiaResultado(membresiaCarga);
            String [][] reglasDisViaje = Calculos.membresiaResultado(membresiaDisViaje);
            String [][] reglasCargaPactual = Calculos.membresiaResultado(membresiaCargaPactual);
            
            String [][] resulReglas = Calculos.calReglas(reglasTmpEspera, reglasTmpViajes, 
                    reglasCarga, reglasDisViaje, reglasCargaPactual);
            
            
            resultado += "\nInferencia\n";
            for(int i=0; i<resulReglas.length; i++){
                resultado += resulReglas[i][0]+"\n"
                          + resulReglas[i][1]+"\n";
            }

            // Prioridad
            double prioridad = 0.0;
            if(resulReglas[1][0] == null){
                prioridad = FuzzyLogic.Centroide(resulReglas[0][0], Double.parseDouble(resulReglas[0][1].trim()));
            }else{
                prioridad = FuzzyLogic.Centroide(resulReglas[0][0], Double.parseDouble(resulReglas[0][1].trim()), 
                        resulReglas[1][0], Double.parseDouble(resulReglas[1][1].trim()));
            }
            
             resultado += "\nPrioridad :"+prioridad;
             
             jTxtAreaResultado.setText(resultado+"\n");
             
             return prioridad;
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgP1 = new javax.swing.ButtonGroup();
        bgP2 = new javax.swing.ButtonGroup();
        bgP3 = new javax.swing.ButtonGroup();
        jPanel10 = new javax.swing.JPanel();
        jRB8 = new javax.swing.JRadioButton();
        jRBP8Arriba = new javax.swing.JRadioButton();
        jRBP8Abajo = new javax.swing.JRadioButton();
        jSP8 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jSPDP8 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jPanelEdificio = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtAreaResultado = new javax.swing.JTextArea();
        jLabel31 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jRBtn1 = new javax.swing.JRadioButton();
        jRBtn3 = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jSPDP1 = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        jSP1 = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        jSPDP3 = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jSP3 = new javax.swing.JSpinner();
        jRBtn5 = new javax.swing.JRadioButton();
        jRBtn7 = new javax.swing.JRadioButton();
        jRBtn9 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSPDP5 = new javax.swing.JSpinner();
        jSPDP7a = new javax.swing.JSpinner();
        jSPDP9 = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSP5 = new javax.swing.JSpinner();
        jSP7a = new javax.swing.JSpinner();
        jSP9 = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        jSPDP11 = new javax.swing.JSpinner();
        jRBtn11 = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        jSP11 = new javax.swing.JSpinner();
        jRBtn13 = new javax.swing.JRadioButton();
        jRBtn15 = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        jSPDP13 = new javax.swing.JSpinner();
        jLabel26 = new javax.swing.JLabel();
        jSP13 = new javax.swing.JSpinner();
        jLabel29 = new javax.swing.JLabel();
        jSPDP15 = new javax.swing.JSpinner();
        jLabel30 = new javax.swing.JLabel();
        jSP15 = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jRBtn2 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jSPD2 = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        jSP2 = new javax.swing.JSpinner();
        jRBtn4 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jSPDP4 = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jSP4 = new javax.swing.JSpinner();
        jRBtn6 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jSPDP6 = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jSP6 = new javax.swing.JSpinner();
        jRBtn8 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jSPDP7 = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jSP7 = new javax.swing.JSpinner();
        jRBtn10 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jSPDP10 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jSP10 = new javax.swing.JSpinner();
        jRBtn12 = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        jSPDP12 = new javax.swing.JSpinner();
        jLabel24 = new javax.swing.JLabel();
        jSP12 = new javax.swing.JSpinner();
        jRBtn14 = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        jSPDP14 = new javax.swing.JSpinner();
        jLabel28 = new javax.swing.JLabel();
        jSP14 = new javax.swing.JSpinner();
        jLabel34 = new javax.swing.JLabel();
        jBtnSiguiente = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuIniciar = new javax.swing.JMenuItem();
        jMenuPausar = new javax.swing.JMenuItem();
        jMenuReanudar = new javax.swing.JMenuItem();
        jMenuDetener = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel10.setBackground(new java.awt.Color(153, 153, 255));

        jRB8.setText("P8");
        jRB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB8ActionPerformed(evt);
            }
        });

        jRBP8Arriba.setText("^");
        jRBP8Arriba.setEnabled(false);

        jRBP8Abajo.setText("v");
        jRBP8Abajo.setEnabled(false);

        jSP8.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));
        jSP8.setEnabled(false);

        jLabel5.setText("Personas:");

        jSPDP8.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        jSPDP8.setEnabled(false);

        jLabel6.setText("Destino:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRB8, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jRBP8Arriba, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRBP8Abajo, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jSPDP8, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSP8, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jRB8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRBP8Abajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRBP8Arriba)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSPDP8)
                        .addComponent(jSP8)))
                .addGap(12, 12, 12))
        );

        jPanelEdificio.setBackground(new java.awt.Color(102, 255, 255));
        jPanelEdificio.setPreferredSize(new java.awt.Dimension(100, 500));

        javax.swing.GroupLayout jPanelEdificioLayout = new javax.swing.GroupLayout(jPanelEdificio);
        jPanelEdificio.setLayout(jPanelEdificioLayout);
        jPanelEdificioLayout.setHorizontalGroup(
            jPanelEdificioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanelEdificioLayout.setVerticalGroup(
            jPanelEdificioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jTxtAreaResultado.setColumns(20);
        jTxtAreaResultado.setRows(5);
        jScrollPane1.setViewportView(jTxtAreaResultado);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jLabel31.setText("Piso 1....15");

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jRBtn1.setText("P1");
        jRBtn1.setEnabled(false);
        jRBtn1.setPreferredSize(new java.awt.Dimension(50, 25));
        jRBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtn1ActionPerformed(evt);
            }
        });

        jRBtn3.setText("P3");
        jRBtn3.setEnabled(false);
        jRBtn3.setPreferredSize(new java.awt.Dimension(50, 25));
        jRBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtn3ActionPerformed(evt);
            }
        });

        jLabel19.setText("Destino:");

        jSPDP1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 15, 1));

        jLabel20.setText("Personas:");

        jSP1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));

        jLabel16.setText("Destino:");

        jSPDP3.setModel(new javax.swing.SpinnerNumberModel(3, 1, 15, 1));

        jLabel15.setText("Personas:");

        jSP3.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));

        jRBtn5.setText("P5");
        jRBtn5.setEnabled(false);
        jRBtn5.setPreferredSize(new java.awt.Dimension(50, 25));
        jRBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtn5ActionPerformed(evt);
            }
        });

        jRBtn7.setText("P7");
        jRBtn7.setEnabled(false);
        jRBtn7.setPreferredSize(new java.awt.Dimension(50, 25));
        jRBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtn7ActionPerformed(evt);
            }
        });

        jRBtn9.setText("P9");
        jRBtn9.setEnabled(false);
        jRBtn9.setPreferredSize(new java.awt.Dimension(50, 25));
        jRBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtn9ActionPerformed(evt);
            }
        });

        jLabel11.setText("Destino:");

        jLabel32.setText("Destino:");

        jLabel3.setText("Destino:");

        jSPDP5.setModel(new javax.swing.SpinnerNumberModel(5, 1, 15, 1));

        jSPDP7a.setModel(new javax.swing.SpinnerNumberModel(7, 1, 15, 1));

        jSPDP9.setModel(new javax.swing.SpinnerNumberModel(9, 1, 15, 1));

        jLabel12.setText("Personas:");

        jLabel33.setText("Personas:");

        jLabel4.setText("Personas:");

        jSP5.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));

        jSP7a.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));

        jSP9.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));

        jLabel21.setText("Destino:");

        jSPDP11.setModel(new javax.swing.SpinnerNumberModel(11, 1, 15, 1));

        jRBtn11.setText("P11");
        jRBtn11.setEnabled(false);
        jRBtn11.setPreferredSize(new java.awt.Dimension(50, 25));
        jRBtn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtn11ActionPerformed(evt);
            }
        });

        jLabel22.setText("Personas:");

        jSP11.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));
        jSP11.setRequestFocusEnabled(false);

        jRBtn13.setText("P13");
        jRBtn13.setEnabled(false);
        jRBtn13.setPreferredSize(new java.awt.Dimension(50, 25));
        jRBtn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtn13ActionPerformed(evt);
            }
        });

        jRBtn15.setEnabled(false);
        jRBtn15.setLabel("P15");
        jRBtn15.setPreferredSize(new java.awt.Dimension(50, 25));
        jRBtn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtn15ActionPerformed(evt);
            }
        });

        jLabel25.setText("Destino:");

        jSPDP13.setModel(new javax.swing.SpinnerNumberModel(13, 1, 15, 1));

        jLabel26.setText("Personas:");

        jSP13.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));
        jSP13.setRequestFocusEnabled(false);

        jLabel29.setText("Destino:");

        jSPDP15.setModel(new javax.swing.SpinnerNumberModel(15, 1, 15, 1));

        jLabel30.setText("Personas:");

        jSP15.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));
        jSP15.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBtn11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSPDP9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSP9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSPDP5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSP5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSPDP7a, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSP7a, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSPDP11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSP11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSPDP3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSPDP1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jSP3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBtn13, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRBtn15, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSPDP15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSPDP13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSP13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSP15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSPDP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jSP3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSPDP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSPDP5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSP5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSPDP7a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSP7a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jSP9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSPDP9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSPDP11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSP11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3))
                    .addComponent(jRBtn11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBtn13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSPDP13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSP13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jSP15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRBtn15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSPDP15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jRBtn1.getAccessibleContext().setAccessibleName("57");
        jRBtn1.getAccessibleContext().setAccessibleDescription("22");
        jRBtn3.getAccessibleContext().setAccessibleName("57");
        jRBtn3.getAccessibleContext().setAccessibleDescription("22");
        jRBtn5.getAccessibleContext().setAccessibleName("57");
        jRBtn5.getAccessibleContext().setAccessibleDescription("22");
        jRBtn7.getAccessibleContext().setAccessibleName("57");
        jRBtn7.getAccessibleContext().setAccessibleDescription("22");
        jRBtn9.getAccessibleContext().setAccessibleName("57");
        jRBtn9.getAccessibleContext().setAccessibleDescription("22");
        jRBtn11.getAccessibleContext().setAccessibleName("57");
        jRBtn11.getAccessibleContext().setAccessibleDescription("22");
        jRBtn13.getAccessibleContext().setAccessibleName("57");
        jRBtn13.getAccessibleContext().setAccessibleDescription("22");
        jRBtn15.getAccessibleContext().setAccessibleName("57");
        jRBtn15.getAccessibleContext().setAccessibleDescription("22");

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        jRBtn2.setText("P2");
        jRBtn2.setEnabled(false);
        jRBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtn2ActionPerformed(evt);
            }
        });

        jLabel17.setText("Destino:");

        jSPD2.setModel(new javax.swing.SpinnerNumberModel(2, 1, 15, 1));

        jLabel18.setText("Personas:");

        jSP2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));

        jRBtn4.setText("P4");
        jRBtn4.setEnabled(false);
        jRBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtn4ActionPerformed(evt);
            }
        });

        jLabel13.setText("Destino:");

        jSPDP4.setModel(new javax.swing.SpinnerNumberModel(4, 1, 15, 1));

        jLabel14.setText("Personas:");

        jSP4.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));

        jRBtn6.setText("P6");
        jRBtn6.setEnabled(false);
        jRBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtn6ActionPerformed(evt);
            }
        });

        jLabel9.setText("Destino:");

        jSPDP6.setModel(new javax.swing.SpinnerNumberModel(6, 1, 15, 1));

        jLabel10.setText("Personas:");

        jSP6.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));

        jRBtn8.setText("P8");
        jRBtn8.setEnabled(false);
        jRBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtn8ActionPerformed(evt);
            }
        });

        jLabel7.setText("Destino:");

        jSPDP7.setModel(new javax.swing.SpinnerNumberModel(8, 1, 15, 1));

        jLabel8.setText("Personas:");

        jSP7.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));

        jRBtn10.setText("P10");
        jRBtn10.setEnabled(false);
        jRBtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtn10ActionPerformed(evt);
            }
        });

        jLabel1.setText("Destino:");

        jSPDP10.setModel(new javax.swing.SpinnerNumberModel(10, 1, 15, 1));

        jLabel2.setText("Personas:");

        jSP10.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));
        jSP10.setRequestFocusEnabled(false);

        jRBtn12.setText("P12");
        jRBtn12.setEnabled(false);
        jRBtn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtn12ActionPerformed(evt);
            }
        });

        jLabel23.setText("Destino:");

        jSPDP12.setModel(new javax.swing.SpinnerNumberModel(12, 1, 15, 1));

        jLabel24.setText("Personas:");

        jSP12.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));
        jSP12.setRequestFocusEnabled(false);

        jRBtn14.setText("P14");
        jRBtn14.setEnabled(false);
        jRBtn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtn14ActionPerformed(evt);
            }
        });

        jLabel27.setText("Destino:");

        jSPDP14.setModel(new javax.swing.SpinnerNumberModel(14, 1, 15, 1));

        jLabel28.setText("Personas:");

        jSP14.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));
        jSP14.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSPDP6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRBtn10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRBtn12, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSPDP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSPD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jSPDP12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jSPDP10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jSPDP7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSP4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(jSP6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSP7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSP10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSP12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSP2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRBtn14, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSPDP14, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSP14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSPD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSPDP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSPDP6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSP6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSP7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSPDP7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSP10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSPDP10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRBtn10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSP12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSPDP12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRBtn12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSPDP14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRBtn14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSP14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        jLabel34.setText("Selecciona el piso destino y la cantidad de personas a subir");

        jBtnSiguiente.setText("Siguiente");
        jBtnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSiguienteActionPerformed(evt);
            }
        });

        jMenu1.setText("Menu");

        jMenuIniciar.setText("Iniciar");
        jMenuIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIniciarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuIniciar);

        jMenuPausar.setText("Pausar");
        jMenuPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPausarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuPausar);

        jMenuReanudar.setText("Reanudar");
        jMenuReanudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuReanudarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuReanudar);

        jMenuDetener.setText("Detener");
        jMenuDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDetenerActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuDetener);

        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanelEdificio, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnSiguiente)
                        .addGap(11, 11, 11)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(260, 260, 260))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(jBtnSiguiente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelEdificio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, 0, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtn1ActionPerformed
        // TODO add your handling code here:
        jSP1.setEnabled(true);
        jSPDP1.setEnabled(true);
        Dibujo.dibujarPersona(0, 50, jPanelEdificio);
        int llamadaElevador = 1;
        int destino = (int) jSPDP1.getValue();
        int posElevador = fl.getX();
        
        if (!((int) jSPDP1.getValue() == llamadaElevador)) {
            // Fuzzy
            double tmpEsperas = Calculos.tmpEspera(llamadaElevador, posElevador);
            double tmpViajes = Calculos.tmpViaje(llamadaElevador, destino);
            double cargas = Calculos.carga((int) jSP1.getValue());
            double distViaje = Calculos.disViaje(llamadaElevador, posElevador);
            double cargaActual = Calculos.cargaActual((int) jSP1.getValue());
            
            resultado += Calculos.resultadosP(llamadaElevador, tmpEsperas, tmpViajes, cargas,
                    distViaje, cargaActual);
            
            resultado += "\n"+llamadaElevador+" -> "+destino+"\n";
            
            double pri = prioridad(tmpEsperas, tmpViajes, cargas, distViaje, cargaActual);
            
            fl.agregarValor(pri, llamadaElevador, destino);
            fl.setPesoEnElevador((int) jSP1.getValue());
  
        } else {
            JOptionPane.showMessageDialog(null, "Indique un destino");
        }
        
        jRBtn1.setSelected(false);

        
    }//GEN-LAST:event_jRBtn1ActionPerformed

    private void jRBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtn2ActionPerformed
        // TODO add your handling code here:
        jSP2.setEnabled(true);
        jSPD2.setEnabled(true);
        Dibujo.dibujarPersona(50, 50, jPanelEdificio);
        int llamadaElevador = 2;
        int destino = (int) jSPD2.getValue();
        int posElevador = fl.getX();
        
        if (!((int) jSPD2.getValue() == llamadaElevador)) {
        double tmpEsperas = Calculos.tmpEspera(llamadaElevador, posElevador);
        double tmpViajes = Calculos.tmpViaje(llamadaElevador, destino);
        double cargas = Calculos.carga((int)jSP2.getValue());
        double distViaje = Calculos.disViaje(llamadaElevador, posElevador);
        double cargaActual = Calculos.cargaActual((int) jSP2.getValue());

        resultado += Calculos.resultadosP(llamadaElevador, tmpEsperas, tmpViajes, cargas,
                                distViaje, cargaActual);
        
        resultado += "\n"+llamadaElevador+" -> "+destino+"\n";
        
         double pri = prioridad(tmpEsperas, tmpViajes, cargas, distViaje, cargaActual);
         fl.agregarValor(pri, llamadaElevador, destino);
         
        } else {
            JOptionPane.showMessageDialog(null, "Indique un destino");
        }
        
        jRBtn2.setSelected(false);
    }//GEN-LAST:event_jRBtn2ActionPerformed

    private void jRBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtn3ActionPerformed
        // TODO add your handling code here:
        jSP3.setEnabled(true);
        jSPDP3.setEnabled(true);
        Dibujo.dibujarPersona(100, 50, jPanelEdificio);
        int llamadaElevador = 3;
        int destino = (int) jSPDP3.getValue();
        int posElevador = fl.getX();
        
        if (!((int) jSPDP3.getValue() == llamadaElevador)) {
        double tmpEsperas = Calculos.tmpEspera(llamadaElevador, posElevador);
        double tmpViajes = Calculos.tmpViaje(llamadaElevador, destino);
        double cargas = Calculos.carga((int)jSP3.getValue());
        double distViaje = Calculos.disViaje(llamadaElevador, posElevador);
        double cargaActual = Calculos.cargaActual((int) jSP3.getValue());
        
        resultado += Calculos.resultadosP(llamadaElevador, tmpEsperas, tmpViajes, cargas,
                                distViaje, cargaActual);
        resultado += "\n"+llamadaElevador+" -> "+destino+"\n";
        
        double pri = prioridad(tmpEsperas, tmpViajes, cargas, distViaje, cargaActual);
        fl.agregarValor(pri, llamadaElevador, destino);
        } else {
            JOptionPane.showMessageDialog(null, "Indique un destino");
        }
        jRBtn3.setSelected(false);
    }//GEN-LAST:event_jRBtn3ActionPerformed

    private void jRBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtn4ActionPerformed
        // TODO add your handling code here:
        jSP4.setEnabled(true);
        jSPDP4.setEnabled(true);
        Dibujo.dibujarPersona(150, 50,jPanelEdificio);
        int llamadaElevador = 4;
        int destino = (int) jSPDP4.getValue();
        int posElevador = fl.getX();
        
        if (!((int) jSPDP4.getValue() == llamadaElevador)) {
        double tmpEsperas = Calculos.tmpEspera(llamadaElevador, posElevador);
        double tmpViajes = Calculos.tmpViaje(llamadaElevador, destino);
         
        double cargas = Calculos.carga((int)jSP4.getValue());
        double distViaje = Calculos.disViaje(llamadaElevador, posElevador);
        double cargaActual = Calculos.cargaActual((int) jSP4.getValue());
       
        resultado += Calculos.resultadosP(llamadaElevador, tmpEsperas, tmpViajes, cargas,
                                distViaje, cargaActual);
        resultado += "\n"+llamadaElevador+" -> "+destino+"\n";
        
        double pri = prioridad(tmpEsperas, tmpViajes, cargas, distViaje, cargaActual);
        fl.agregarValor(pri, llamadaElevador, destino);
        } else {
            JOptionPane.showMessageDialog(null, "Indique un destino");
        }
         jRBtn4.setSelected(false);
    }//GEN-LAST:event_jRBtn4ActionPerformed

    private void jRBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtn5ActionPerformed
        // TODO add your handling code here:
        jSP5.setEnabled(true);
        jSPDP5.setEnabled(true);
        Dibujo.dibujarPersona(200, 50, jPanelEdificio);
        int llamadaElevador = 5;
        int destino = (int) jSPDP5.getValue();
        int posElevador = fl.getX();
        
        if (!((int) jSPDP5.getValue() == llamadaElevador)) {
        double tmpEsperas = Calculos.tmpEspera(llamadaElevador, posElevador);
        double tmpViajes = Calculos.tmpViaje(llamadaElevador, destino);
        double cargas = Calculos.carga((int)jSP5.getValue());
        double distViaje = Calculos.disViaje(llamadaElevador, posElevador);
        double cargaActual = Calculos.cargaActual((int) jSP5.getValue());
        
        resultado += Calculos.resultadosP(llamadaElevador, tmpEsperas, tmpViajes, cargas,
                                distViaje, cargaActual);
        resultado += "\n"+llamadaElevador+" -> "+destino+"\n";
        
         double pri = prioridad(tmpEsperas, tmpViajes, cargas, distViaje, cargaActual);
         fl.agregarValor(pri, llamadaElevador, destino);
        } else {
            JOptionPane.showMessageDialog(null, "Indique un destino");
        }
       jRBtn5.setSelected(false);
    }//GEN-LAST:event_jRBtn5ActionPerformed

    private void jRBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtn6ActionPerformed
        // TODO add your handling code here:
        jSP6.setEnabled(true);
        jSPDP6.setEnabled(true);
        Dibujo.dibujarPersona(250, 50,jPanelEdificio);
        int llamadaElevador = 6;
        int destino = (int) jSPDP6.getValue();
        int posElevador = fl.getX();
        
        
        if (!((int) jSPDP6.getValue() == llamadaElevador)) {
        double tmpEsperas = Calculos.tmpEspera(llamadaElevador, posElevador);
        double tmpViajes = Calculos.tmpViaje(llamadaElevador, destino);
        double cargas = Calculos.carga((int)jSP6.getValue());
        double distViaje = Calculos.disViaje(llamadaElevador, posElevador);
        double cargaActual = Calculos.cargaActual((int) jSP6.getValue());
        
        resultado += Calculos.resultadosP(llamadaElevador, tmpEsperas, tmpViajes, cargas,
                                distViaje, cargaActual);
        resultado += "\n"+llamadaElevador+" -> "+destino+"\n";
        
         double pri = prioridad(tmpEsperas, tmpViajes, cargas, distViaje, cargaActual);
         fl.agregarValor(pri, llamadaElevador, destino);

        } else {
            JOptionPane.showMessageDialog(null, "Indique un destino");
        }
        jRBtn6.setSelected(false);
    }//GEN-LAST:event_jRBtn6ActionPerformed

    private void jRBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtn8ActionPerformed
        // TODO add your handling code here:
        jSP8.setEnabled(true);
        jSPDP8.setEnabled(true);
        Dibujo.dibujarPersona(350, 50,jPanelEdificio);
        int llamadaElevador = 8;
        int destino = (int) jSPDP8.getValue();
        int posElevador = fl.getX();
        
        if (!((int) jSPDP8.getValue() == llamadaElevador)) {
        double tmpEsperas = Calculos.tmpEspera(llamadaElevador, posElevador);
        double tmpViajes = Calculos.tmpViaje(llamadaElevador, destino);
        double cargas = Calculos.carga((int)jSP7.getValue());
        double distViaje = Calculos.disViaje(llamadaElevador, posElevador);
        double cargaActual = Calculos.cargaActual((int) jSP8.getValue());

        resultado += Calculos.resultadosP(llamadaElevador, tmpEsperas, tmpViajes, cargas,
                                distViaje, cargaActual);
        resultado += "\n"+llamadaElevador+" -> "+destino+"\n";
        
        double pri = prioridad(tmpEsperas, tmpViajes, cargas, distViaje, cargaActual);
        fl.agregarValor(pri, llamadaElevador, destino);
        } else {
            JOptionPane.showMessageDialog(null, "Indique un destino");
        }
        jRBtn8.setSelected(false);
    }//GEN-LAST:event_jRBtn8ActionPerformed

    private void jRB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB8ActionPerformed
        // TODO add your handling code here:
        jSP8.setEnabled(true);
        jSPDP8.setEnabled(true);
        Dibujo.dibujarPersona(400, 50, jPanelEdificio);
        int llamadaElevador = 8;
        int destino = (int) jSPDP8.getValue();
        int posElevador = fl.getX();
        
        if (!((int) jSPDP8.getValue() == llamadaElevador)) {
        double tmpEsperas = Calculos.tmpEspera(llamadaElevador, posElevador);
        double tmpViajes = Calculos.tmpViaje(llamadaElevador, destino);
        double cargas = Calculos.carga((int)jSP8.getValue());
        double distViaje = Calculos.disViaje(llamadaElevador, posElevador);
        double cargaActual = Calculos.cargaActual((int) jSP8.getValue());

        resultado += Calculos.resultadosP(llamadaElevador, tmpEsperas, tmpViajes, cargas,
                                distViaje, cargaActual);
        resultado += "\n"+llamadaElevador+" -> "+destino+"\n";
        
        double pri = prioridad(tmpEsperas, tmpViajes, cargas, distViaje, cargaActual);
        fl.agregarValor(pri, llamadaElevador, destino);
        } else {
            JOptionPane.showMessageDialog(null, "Indique un destino");
        }
         jRBtn8.setSelected(false);
    }//GEN-LAST:event_jRB8ActionPerformed

    private void jRBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtn9ActionPerformed
        // TODO add your handling code here:
        jSP9.setEnabled(true);
        jSPDP9.setEnabled(true);
        Dibujo.dibujarPersona(400, 50, jPanelEdificio);
        int llamadaElevador = 9;
        int destino = (int) jSPDP9.getValue();
        int posElevador = fl.getX();
        
        
        if (!((int) jSPDP9.getValue() == llamadaElevador)) {
        double tmpEsperas = Calculos.tmpEspera(llamadaElevador, posElevador);
        double tmpViajes = Calculos.tmpViaje(llamadaElevador, destino);
        double cargas = Calculos.carga((int)jSP9.getValue());
        double distViaje = Calculos.disViaje(llamadaElevador, posElevador);
        double cargaActual = Calculos.cargaActual((int) jSP9.getValue());

        resultado += Calculos.resultadosP(llamadaElevador, tmpEsperas, tmpViajes, cargas,
                                distViaje, cargaActual);
        resultado += "\n"+llamadaElevador+" -> "+destino+"\n"; 
        
        double pri = prioridad(tmpEsperas, tmpViajes, cargas, distViaje, cargaActual);
        fl.agregarValor(pri, llamadaElevador, destino);

        } else {
            JOptionPane.showMessageDialog(null, "Indique un destino");
        }
         jRBtn9.setSelected(false);
    }//GEN-LAST:event_jRBtn9ActionPerformed

    private void jRBtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtn10ActionPerformed
        // TODO add your handling code here:
        jSP10.setEnabled(true);
        jSPDP10.setEnabled(true);
        Dibujo.dibujarPersona(450, 50, jPanelEdificio);
        int llamadaElevador = 10;
        int destino = (int) jSPDP10.getValue();
        int posElevador = fl.getX();
        
        if (!((int) jSPDP10.getValue() == llamadaElevador)) {
        double tmpEsperas = Calculos.tmpEspera(llamadaElevador, posElevador);
        double tmpViajes = Calculos.tmpViaje(llamadaElevador, destino);
        double cargas = Calculos.carga((int)jSP10.getValue());
        double distViaje = Calculos.disViaje(llamadaElevador, posElevador);
        double cargaActual = Calculos.cargaActual((int) jSP10.getValue());

        resultado += Calculos.resultadosP(llamadaElevador, tmpEsperas, tmpViajes, cargas,
                                distViaje, cargaActual);
        resultado += "\n"+llamadaElevador+" -> "+destino+"\n";
        
        double pri = prioridad(tmpEsperas, tmpViajes, cargas, distViaje, cargaActual);
        fl.agregarValor(pri, llamadaElevador, destino);

        jTxtAreaResultado.setText(resultado);
        } else {
            JOptionPane.showMessageDialog(null, "Indique un destino");
        }
        jRBtn10.setSelected(false);
    }//GEN-LAST:event_jRBtn10ActionPerformed

    private void jRBtn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtn11ActionPerformed
        // TODO add your handling code here:
        jSP11.setEnabled(true);
        jSPDP11.setEnabled(true);
        Dibujo.dibujarPersona(500, 50, jPanelEdificio);
        int llamadaElevador = 11;
        int destino = (int) jSPDP11.getValue();
        int posElevador = fl.getX();
        
        if (!((int) jSPDP11.getValue() == llamadaElevador)) {
        double tmpEsperas = Calculos.tmpEspera(llamadaElevador, posElevador);
        double tmpViajes = Calculos.tmpViaje(llamadaElevador, destino);
        double cargas = Calculos.carga((int)jSP11.getValue());
        double distViaje = Calculos.disViaje(llamadaElevador, posElevador);
        double cargaActual = Calculos.cargaActual((int) jSP11.getValue());

        resultado += Calculos.resultadosP(llamadaElevador, tmpEsperas, tmpViajes, cargas,
                                distViaje, cargaActual);
        resultado += "\n"+llamadaElevador+" -> "+destino+"\n";
        
        double pri = prioridad(tmpEsperas, tmpViajes, cargas, distViaje, cargaActual);
        fl.agregarValor(pri, llamadaElevador, destino);
 
        } else {
            JOptionPane.showMessageDialog(null, "Indique un destino");
        }
         jRBtn11.setSelected(false);
    }//GEN-LAST:event_jRBtn11ActionPerformed

    private void jRBtn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtn12ActionPerformed
        // TODO add your handling code here:
        jSP12.setEnabled(true);
        jSPDP12.setEnabled(true);
        Dibujo.dibujarPersona(550, 50, jPanelEdificio);
        int llamadaElevador = 12;
        int destino = (int) jSPDP12.getValue();
        int posElevador = fl.getX();
        
        if (!((int) jSPDP12.getValue() == llamadaElevador)) {
        double tmpEsperas = Calculos.tmpEspera(llamadaElevador, posElevador);
        double tmpViajes = Calculos.tmpViaje(llamadaElevador, destino);
        double cargas = Calculos.carga((int)jSP12.getValue());
        double distViaje = Calculos.disViaje(llamadaElevador, posElevador);
        double cargaActual = Calculos.cargaActual((int) jSP12.getValue());

        resultado += Calculos.resultadosP(llamadaElevador, tmpEsperas, tmpViajes, cargas,
                                distViaje, cargaActual);
        resultado += "\n"+llamadaElevador+" -> "+destino+"\n";
        
        double pri = prioridad(tmpEsperas, tmpViajes, cargas, distViaje, cargaActual);
        fl.agregarValor(pri, llamadaElevador, destino);

        } else {
            JOptionPane.showMessageDialog(null, "Indique un destino");
        }
        jRBtn12.setSelected(false);
    }//GEN-LAST:event_jRBtn12ActionPerformed

    private void jRBtn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtn13ActionPerformed
        // TODO add your handling code here:
        jSP13.setEnabled(true);
        jSPDP13.setEnabled(true);
        Dibujo.dibujarPersona(600, 50, jPanelEdificio);
        int llamadaElevador = 13;
        int destino = (int) jSPDP13.getValue();
        int posElevador = fl.getX();
        
        if (!((int) jSPDP13.getValue() == llamadaElevador)) {
        double tmpEsperas = Calculos.tmpEspera(llamadaElevador, posElevador);
        double tmpViajes = Calculos.tmpViaje(llamadaElevador, destino);
        double cargas = Calculos.carga((int)jSP13.getValue());
        double distViaje = Calculos.disViaje(llamadaElevador, posElevador);
        double cargaActual = Calculos.cargaActual((int) jSP13.getValue());

        resultado += Calculos.resultadosP(llamadaElevador, tmpEsperas, tmpViajes, cargas,
                                distViaje, cargaActual);
        resultado += "\n"+llamadaElevador+" -> "+destino+"\n";
        
        double pri = prioridad(tmpEsperas, tmpViajes, cargas, distViaje, cargaActual);
        fl.agregarValor(pri, llamadaElevador, destino);
        
        } else {
            JOptionPane.showMessageDialog(null, "Indique un destino");
        }
         jRBtn13.setSelected(false);
    }//GEN-LAST:event_jRBtn13ActionPerformed

    private void jRBtn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtn14ActionPerformed
        // TODO add your handling code here:
        jSP14.setEnabled(true);
        jSPDP14.setEnabled(true);
        Dibujo.dibujarPersona(650, 50, jPanelEdificio);
        int llamadaElevador = 14;
        int destino = (int) jSPDP14.getValue();
        int posElevador = fl.getX();
        
        if (!((int) jSPDP14.getValue() == llamadaElevador)) {
        double tmpEsperas = Calculos.tmpEspera(llamadaElevador, posElevador);
        double tmpViajes = Calculos.tmpViaje(llamadaElevador, destino);
         
        double cargas = Calculos.carga((int)jSP14.getValue());
        double distViaje = Calculos.disViaje(llamadaElevador, posElevador);
        double cargaActual = Calculos.cargaActual((int) jSP14.getValue());

        resultado += Calculos.resultadosP(llamadaElevador, tmpEsperas, tmpViajes, cargas,
                                distViaje, cargaActual);
        resultado += "\n"+llamadaElevador+" -> "+destino+"\n";
        
        double pri = prioridad(tmpEsperas, tmpViajes, cargas, distViaje, cargaActual);
        fl.agregarValor(pri, llamadaElevador, destino);

        } else {
            JOptionPane.showMessageDialog(null, "Indique un destino");
        }
        jRBtn14.setSelected(false);
    }//GEN-LAST:event_jRBtn14ActionPerformed

    private void jRBtn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtn15ActionPerformed
        // TODO add your handling code here:
        jSP15.setEnabled(true);
        jSPDP15.setEnabled(true);
        Dibujo.dibujarPersona(700, 50, jPanelEdificio);
        int llamadaElevador = 15;
        int destino = (int) jSPDP15.getValue();
        int posElevador = fl.getX();
        
        if (!((int) jSPDP15.getValue() == llamadaElevador)) {
        double tmpEsperas = Calculos.tmpEspera(llamadaElevador, posElevador);
        double tmpViajes = Calculos.tmpViaje(llamadaElevador, destino);
        double cargas = Calculos.carga((int)jSP15.getValue());
        double distViaje = Calculos.disViaje(llamadaElevador, posElevador);
        double cargaActual = Calculos.cargaActual((int) jSP15.getValue());

        resultado += Calculos.resultadosP(llamadaElevador, tmpEsperas, tmpViajes, cargas,
                                distViaje, cargaActual);
        resultado += "\n"+llamadaElevador+" -> "+destino+"\n";
        
        double pri = prioridad(tmpEsperas, tmpViajes, cargas, distViaje, cargaActual);
        fl.agregarValor(pri, llamadaElevador, destino);
        
        } else {
            JOptionPane.showMessageDialog(null, "Indique un destino");
        }
         jRBtn15.setSelected(false);
    }//GEN-LAST:event_jRBtn15ActionPerformed

    private void jRBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtn7ActionPerformed
        // TODO add your handling code here:
        jSP7a.setEnabled(true);
        jSPDP7a.setEnabled(true);
        Dibujo.dibujarPersona(300, 50, jPanelEdificio);
        int llamadaElevador = 7;
        int destino = (int) jSPDP7a.getValue();
        int posElevador = fl.getX();
        
        if (!((int) jSPDP7a.getValue() == llamadaElevador)) {
        double tmpEsperas = Calculos.tmpEspera(llamadaElevador, posElevador);
        double tmpViajes = Calculos.tmpViaje(llamadaElevador, destino);
        double cargas = Calculos.carga((int)jSP7.getValue());
        double distViaje = Calculos.disViaje(llamadaElevador, posElevador);
        double cargaActual = Calculos.cargaActual((int) jSP7a.getValue());

        resultado += Calculos.resultadosP(llamadaElevador, tmpEsperas, tmpViajes, cargas,
                                distViaje, cargaActual);
        resultado += "\n"+llamadaElevador+" -> "+destino+"\n";
        
        double pri = prioridad(tmpEsperas, tmpViajes, cargas, distViaje, cargaActual);
        fl.agregarValor(pri, llamadaElevador, destino);
        } else {
            JOptionPane.showMessageDialog(null, "Indique un destino");
        }
         jRBtn7.setSelected(false);
    }//GEN-LAST:event_jRBtn7ActionPerformed

    private void jMenuIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIniciarActionPerformed
        resultado = "";
        
        fl = new FuzzyLogic(jPanelEdificio);
        Calculos.setPesoEleva(0);
        Dibujo.dibujarEdificio(jPanelEdificio);
        fl.start();
        //fl.movimientoPrioridad(movPriori);
        
        //x = piso en donde se encuentra el elevador
        //y = posicion del elevador
        // x+= 50 para ir del piso 15 al 14 ....
        Dibujo.dibujarElevador(0, 0, jPanelEdificio);
        
        jRBtn1.setEnabled(true);
        jRBtn2.setEnabled(true);
        jRBtn3.setEnabled(true);
        jRBtn4.setEnabled(true);
        jRBtn5.setEnabled(true);
        jRBtn6.setEnabled(true);
        jRBtn7.setEnabled(true);
        jRBtn8.setEnabled(true);
        jRBtn9.setEnabled(true);
        jRBtn10.setEnabled(true);
        jRBtn11.setEnabled(true);
        jRBtn12.setEnabled(true);
        jRBtn13.setEnabled(true);
        jRBtn14.setEnabled(true);
        jRBtn15.setEnabled(true);
        
        jTxtAreaResultado.setText("");
        jRBtn1.setSelected(false);
        jRBtn2.setSelected(false);
        jRBtn3.setSelected(false);
        jRBtn4.setSelected(false);
        jRBtn5.setSelected(false);
        jRBtn6.setSelected(false);
        jRBtn7.setSelected(false);
        jRBtn8.setSelected(false);
        jRBtn9.setSelected(false);
        jRBtn10.setSelected(false);
        jRBtn11.setSelected(false);
        jRBtn12.setSelected(false);
        jRBtn13.setSelected(false);
        jRBtn14.setSelected(false);
        jRBtn15.setSelected(false);
    }//GEN-LAST:event_jMenuIniciarActionPerformed

    private void jMenuPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPausarActionPerformed
        // TODO add your handling code here:
        if(fl != null){
            fl.suspend();
        }else {
            JOptionPane.showMessageDialog(null, "No se ha iniciado el programa.");
        }
    }//GEN-LAST:event_jMenuPausarActionPerformed

    private void jMenuDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDetenerActionPerformed
        // TODO add your handling code here:
        if(fl != null){
            fl.stop();
            inicio = false;
         }else {
            JOptionPane.showMessageDialog(null, "No se ha iniciado el programa.");
        }
    }//GEN-LAST:event_jMenuDetenerActionPerformed

    private void jMenuReanudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuReanudarActionPerformed
        // TODO add your handling code here:
         if(fl != null){
            fl.resume();
         }else {
            JOptionPane.showMessageDialog(null, "No se ha iniciado el programa.");
        }
    }//GEN-LAST:event_jMenuReanudarActionPerformed

    private void jBtnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSiguienteActionPerformed
        // TODO add your handling code here:
         fl.setTermino(false);
    }//GEN-LAST:event_jBtnSiguienteActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(U4_LD_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(U4_LD_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(U4_LD_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(U4_LD_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new U4_LD_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgP1;
    private javax.swing.ButtonGroup bgP2;
    private javax.swing.ButtonGroup bgP3;
    private javax.swing.JButton jBtnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuDetener;
    private javax.swing.JMenuItem jMenuIniciar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuPausar;
    private javax.swing.JMenuItem jMenuReanudar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelEdificio;
    private javax.swing.JRadioButton jRB8;
    private javax.swing.JRadioButton jRBP8Abajo;
    private javax.swing.JRadioButton jRBP8Arriba;
    private javax.swing.JRadioButton jRBtn1;
    private javax.swing.JRadioButton jRBtn10;
    private javax.swing.JRadioButton jRBtn11;
    private javax.swing.JRadioButton jRBtn12;
    private javax.swing.JRadioButton jRBtn13;
    private javax.swing.JRadioButton jRBtn14;
    private javax.swing.JRadioButton jRBtn15;
    private javax.swing.JRadioButton jRBtn2;
    private javax.swing.JRadioButton jRBtn3;
    private javax.swing.JRadioButton jRBtn4;
    private javax.swing.JRadioButton jRBtn5;
    private javax.swing.JRadioButton jRBtn6;
    private javax.swing.JRadioButton jRBtn7;
    private javax.swing.JRadioButton jRBtn8;
    private javax.swing.JRadioButton jRBtn9;
    private javax.swing.JSpinner jSP1;
    private javax.swing.JSpinner jSP10;
    private javax.swing.JSpinner jSP11;
    private javax.swing.JSpinner jSP12;
    private javax.swing.JSpinner jSP13;
    private javax.swing.JSpinner jSP14;
    private javax.swing.JSpinner jSP15;
    private javax.swing.JSpinner jSP2;
    private javax.swing.JSpinner jSP3;
    private javax.swing.JSpinner jSP4;
    private javax.swing.JSpinner jSP5;
    private javax.swing.JSpinner jSP6;
    private javax.swing.JSpinner jSP7;
    private javax.swing.JSpinner jSP7a;
    private javax.swing.JSpinner jSP8;
    private javax.swing.JSpinner jSP9;
    private javax.swing.JSpinner jSPD2;
    private javax.swing.JSpinner jSPDP1;
    private javax.swing.JSpinner jSPDP10;
    private javax.swing.JSpinner jSPDP11;
    private javax.swing.JSpinner jSPDP12;
    private javax.swing.JSpinner jSPDP13;
    private javax.swing.JSpinner jSPDP14;
    private javax.swing.JSpinner jSPDP15;
    private javax.swing.JSpinner jSPDP3;
    private javax.swing.JSpinner jSPDP4;
    private javax.swing.JSpinner jSPDP5;
    private javax.swing.JSpinner jSPDP6;
    private javax.swing.JSpinner jSPDP7;
    private javax.swing.JSpinner jSPDP7a;
    private javax.swing.JSpinner jSPDP8;
    private javax.swing.JSpinner jSPDP9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxtAreaResultado;
    // End of variables declaration//GEN-END:variables
}
